/* src/config_cbc.h.  Generated by configure.  */
/* src/config_cbc.h.in. */

/* Version number of project */
#define CBC_VERSION "trunk"

/* Major Version number of project */
#define CBC_VERSION_MAJOR 9999

/* Minor Version number of project */
#define CBC_VERSION_MINOR 9999

/* Release Version number of project */
#define CBC_VERSION_RELEASE 9999
