/* src/config_clp.h.  Generated by configure.  */
/* src/config_clp.h.in.  */

/* Version number of project */
#define CLP_VERSION "1.14"

/* Major Version number of project */
#define CLP_VERSION_MAJOR 1

/* Minor Version number of project */
#define CLP_VERSION_MINOR 14

/* Release Version number of project */
#define CLP_VERSION_RELEASE 9999
